### ISSUE TITLE
SampleProducer.run().weighted_pick() might not work as expected

### ISSUE THREAD

**Issue by ppetoumenos** [ChrisCummins/clgen#120]
np.searchsorted() assumes the input array is already sorted.
The argument we provide when we call it in weighted_pick() is the output of np.cumsum() which will be sorted only if all the weights are positive.

If this is true then we're fine. Otherwise the probability of selecting a character is not proportional to its weight.

**Comment by ChrisCummins** [comment]
hmm, I havne't looked at the sampler code in quite some time. If I remember correctly, probabilities are in the range [0,1]? I'm not sure I'm remembering that right, though it would be easy to check by inserting `assert(all(x >= 0 for x in weights))` into weighted pick and running the sampler on a trained model.

Nevertheless, I see that I never finished implementing the `temperature` parameter. I should take a look at this.

**Comment by ppetoumenos** [comment]
Indeed, I was wondering what `temperature` does :). About the weight, I noticed the problem when I copied the code to a different application where weights could be negative.

**Comment by ChrisCummins** [comment]
In the [char-rnn implementation](https://github.com/jcjohnson/torch-rnn/blob/master/LanguageModel.lua#L194-L196), temperature allows you to control sampling noise.

For cases with negative values, could you get away with applying an `+= weights.min()` offset?

**Comment by ChrisCummins** [comment]
There was no error after an hour running the GitHub corpus with this sampler:

```patch
diff --git a/clgen/_sampler.py b/clgen/_sampler.py
index 1ea23a0..45b45ff 100644
--- a/clgen/_sampler.py
+++ b/clgen/_sampler.py
@@ -120,6 +120,7 @@ class SampleProducer(Thread):
             saver.restore(sess, ckpt.model_checkpoint_path)

             def weighted_pick(weights, temperature):
+                assert all(x >= 0 for x in weights)
                 t = np.cumsum(weights)
                 s = np.sum(weights)
                 return int(np.searchsorted(t, np.random.rand(1) * s))
```

so closing this, but I'll add a comment as a reminder in case I make changes. Thanks for the catch!
