### ISSUE TITLE
_download_opencl_file() missing 1 required positional argument: 'stack'

### ISSUE THREAD

**Issue by alexanderb14** [ChrisCummins/clgen#125]
Using the fetch module with "clgen fetch github db.db" as invocation, I get the error above.
It's cause by the following calls:

`_download_opencl_file(github_token, repo, include_url) `
`download_file_cb(github_token, repo, file.url)`

to the following function signature: 

`def _download_opencl_file(github_token: str, repo, url: str, stack: List[str]) -> str:`

**Comment by ChrisCummins** [comment]
Closing, see #126 .
