### ISSUE TITLE
'include_re' is not defined

### ISSUE THREAD

**Issue by alexanderb14** [ChrisCummins/clgen#126]
Using the fetch module with "clgen fetch github db.db" as invocation, I get the error above.

The problem is that include_re is used in the _download_opencl_file function, but actually isn't in the scope.

**Comment by ChrisCummins** [comment]
Hey Alexander, sorry for the slow reply, I’ve been travelling.

Thanks for the reports! I was never very happy with the `fetch` module and it has been somewhat neglected. I’ll get around to fixing the issues you reported. In the meantime, you may be interested in a new tool I’ve written which offers a much cleaner method for building corpuses from github:

https://github.com/ChrisCummins/phd/tree/master/datasets/github/scrape_repos

The new tool serves the same purpose, but is much more extensible. To generate a corpus of OpenCL files from GitHub, you could use a clone list like this:

https://github.com/ChrisCummins/phd/blob/master/experimental/deeplearning/polyglot/clone_lists/opencl.pbtxt 

Cheers,
Chris

**Comment by ChrisCummins** [comment]
Closing this as a "wontfix" as the affected code is superceded by https://github.com/ChrisCummins/phd/tree/master/datasets/github/scrape_repos
