### ISSUE TITLE
how to get the output of sampling?

### ISSUE THREAD

**Issue by bwtang** [ChrisCummins/clgen#127]
Hello, I have read your paper and followed the online document to install the project. And then I extracted the tiny train data in the path "./clgen/test/data/tiny.tar.bz2" and used the command like your description "clgen sample model.json sampler.json". I see the output of training process, but I didn't see any output about the sampling.  Am I wrong to use it or I need other command options to get the sampling output? 
![image](https://user-images.githubusercontent.com/7463514/46463295-2c111780-c7f6-11e8-9c86-e7379c3d2fe9.png)

**Comment by ChrisCummins** [comment]
Hi! I haven’t used this repo in a while as I have moved all upstream development to here:

https://github.com/ChrisCummins/phd/tree/master/deeplearning/clgen

However, if I remember correctly the samples are written to an SQLite database in the `~/.cache/clgen` directory, and there’s a command to dump the SQLite database to a text file, which you can check the usage of with `clgen dump --help`. Sorry I can’t remember off the top of my head the exact invocation.

Cheers,
Chris

**Comment by bwtang** [comment]
Thank you very much! I found the SQLite database in the `~/.cache/clgen/0.4.x/sampler/` directory, and dumped the output of sampling successfully! By the way, I wonder if your new repo has some new features or other applications, because I want to follow your work to do some research about the AI code generating. Your work is really cool!

Cheers,
Bowen Tang

**Comment by ChrisCummins** [comment]
Closing as fixed.
