### ISSUE TITLE
Where is INSTALL.md?

### ISSUE THREAD

**Issue by kkysen** [ChrisCummins/clgen#137]
I think you may have forgotten to upload `INSTALL.md`.  The `README.md` says to follow its instructions to build everything, but there's no `INSTALL.md` file anywhere.  Can you add it?

**Comment by ChrisCummins** [comment]
Hi @kkysen , thanks for the report! My apologies, I had misconfigured the export of this repo. INSTALL.md is there now.

Cheers,
Chris
