### ISSUE TITLE
`pip --upgrade pip` doesn't work from old python versions

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/clgen#47]
Instead, the build system should fetch and run [get-pip.py](https://bootstrap.pypa.io/get-pip.py).

**Comment by ppetoumenos** [comment]
More properly, it doesn't work if the old version comes from the OS'es packages which pip is not allowed to replace. Perhaps we could install the new version for the root user only, without replacing the system pip

**Comment by ChrisCummins** [comment]
Do you know how to do a root-only pip install?

Currently I'm imagining something like this:
```py
if pip.__version__ < whatever_version_introduced_the_binary_only_flag
  run_get_pip()  # presumably replaces the system pip, could be nasty
else:
  pip_upgrade()
```

**Comment by ppetoumenos** [comment]
sudo -H pip install --upgrade --user pip

It installs pip in a user directory. For ubuntu at least that's /root/.local/bin and it's already in the path. I just tried it on my laptop and sudo -H pip -V returns a newer version than pip -V

**Comment by ChrisCummins** [comment]
Interesting thanks! I think in Zheng's case it was the pip --upgrade that
was failing, so we may still need to the pip upgrade first perhaps?

**Comment by ppetoumenos** [comment]
It was pip --upgrade failing, but with the message:
"Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS"
Upgrade works fine, but not if there is an equivalent module installed through the package manager

get_pip will work fine if there is no pip installed, but I'm a little bit hesitant to replace a package installed by the package manager without going through the package manager.

**Comment by ChrisCummins** [comment]
Given that [others](https://github.com/pypa/pip/issues/2964) have been having the same issue, how about just `pip --upgrade pip || get-pip`?

**Comment by ChrisCummins** [comment]
Redundant as of #72.
